#!/bin/sh /etc/rc.common
# "new(er)" style init script
# Look at /lib/functions/service.sh on a running system for explanations of what other SERVICE_
# options you can use, and when you might want them.

START=99
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

APP=rclone
SCRIPT_PATH=/bin/$APP
FROM_DIR=alist:/
MOUNT_DIR=/mnt/alist

LOG_FILE_PATH=/tmp/${APP}.log

start() {
  echo -e "LOG_FILE_PATH: $LOG_FILE_PATH"
  mkdir -p $MOUNT_DIR
  $SCRIPT_PATH mount $FROM_DIR  $MOUNT_DIR --cache-dir /tmp --allow-other --vfs-cache-mode writes --header "Referer:https://www.aliyundrive.com/drive" &> $LOG_FILE_PATH &
}

stop() {
  killall $APP
}

restart() {
  stop
  start
}

